//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductID { get; set; }
        public string ProductSKU { get; set; }
        public double ProductPrice { get; set; }
        public double ProductWeight { get; set; }
        public string ProductThumb { get; set; }
        public string ProductImage { get; set; }
        public Nullable<int> ProductCategoryID { get; set; }
        public string ProductLocation { get; set; }
        public string ProductLongDesc { get; set; }
        public string ProductShortDesc { get; set; }
        public string ProductName { get; set; }
        public string ProductCartDesc { get; set; }
    }
}
