//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductImage
    {
        public int ImageId { get; set; }
        public string ContainerName { get; set; }
        public string ImageName { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string ImageType { get; set; }
        public string ImageFormat { get; set; }
    }
}
